version: '3.9'

services:
  web:
    build: ./boilerplate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/boilerplate
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
